export enum Role {
    SUPER_ADMIN = 'SUPER_ADMIN',
    MEDICAL_REVIEWER = 'MEDICAL_REVIEWER',
    OPERATIONS_ADMIN = 'OPERATIONS_ADMIN',
    VENDOR_MANAGER = 'VENDOR_MANAGER',
    FINANCE_ADMIN = 'FINANCE_ADMIN',
    VENDOR = 'VENDOR',
    USER = 'USER'
}
