import { Injectable, Inject } from '@nestjs/common';
import { PricingPlan } from '../entities/pricing-plan.entity';
import type { IPricingPlanRepository } from '../repositories/pricing-plan.repository.interface';
import { AppointmentType } from '@prisma/client';
import { CreatePricingPlanParams, UpdatePricingPlanParams } from 'src/utils/type';

@Injectable()
export class PricingPlanService {
  constructor(
    @Inject('IPricingPlanRepository')
    private readonly pricingPlanRepository: IPricingPlanRepository,
  ) {}

  async findAll(): Promise<PricingPlan[]> {
    return this.pricingPlanRepository.findAll();
  }

  async findActive(): Promise<PricingPlan[]> {
    return this.pricingPlanRepository.findActive();
  }

  // 🚀 Added/Mapped for Controller Sync
  async getActivePlans(): Promise<PricingPlan[]> {
    return this.findActive();
  }

  async findByType(type: AppointmentType): Promise<PricingPlan[]> {
    return this.pricingPlanRepository.findByType(type);
  }

  async findOne(id: string): Promise<PricingPlan | null> {
    return this.pricingPlanRepository.findById(id);
  }


async create(params: CreatePricingPlanParams): Promise<PricingPlan> {
  const plan = new PricingPlan({
    id: '', // ID will be generated by database
    name: params.name,
    type: params.type,
    price: params.price,
    durationDays: params.durationDays,
    appointmentLimit: params.appointmentLimit,
    isInstantSession: params.isInstantSession,
    description: params.description,
    isActive: params.isActive ?? true
  });
  return this.pricingPlanRepository.create(plan);
}

  async update(id: string, params: UpdatePricingPlanParams): Promise<PricingPlan> {
    return this.pricingPlanRepository.update(id, params);
  }

  async delete(id: string): Promise<void> {
    return this.pricingPlanRepository.delete(id);
  }

  /**
   * 🛡️ UPDATED SEED LOGIC:
   * You can add your full list of frontend plans here.
   * Once seeded, the frontend will automatically fetch these via the controller.
   */
  async seedDefaultPricingPlans(): Promise<PricingPlan[]> {
    const defaultPlans = [
      {
        id: '001',
        name: 'Starter Care Plan',
        type: 'STARTER_PLAN',
        price: 3000,
        description: ['Comprehensive care plan for the first month'],
        isActive: true
      },
      {
        id: '002',
        name: 'Instant Specialist Session',
        type: 'INSTANT_SESSION',
        price: 15000,
        description: ['One-time consultation with a specialist'],
        isActive: true
      },
      {
        id: '003',
        name: 'Premium Monthly',
        type: 'PREMIUM_PLAN',
        price: 30000,
        description: ['Unlimited specialist access for 30 days'],
        isActive: true
      }
      // 💡 You can add more plans here to match your frontend exactly!
    ];

    const results: PricingPlan[] = [];
    for (const planData of defaultPlans) {
        const created = await this.create(planData as any);
        results.push(created);
    }
    return results;
  }
}